### ISSUE TITLE
FetchSurveysScheduler :: Racing condition and dead timer :: crash

### ISSUE THREAD

**Issue by r1c4r60** [qualaroo/QualarooSDKiOS#10]
**Crash log:**

destroy value witness for Qualaroo.Survey 
Background Thread 19 - Crashed

```
destroy value witness for Qualaroo.Survey <compiler-generated>:0
libswiftCore.dylib
swift_arrayDestroy
libswiftCore.dylib
Swift._ContiguousArrayStorage.__deallocating_deinit
libswiftCore.dylib
_swift_release_dealloc

closure #1 (Qualaroo.FetchSurveysResult) -> () in Qualaroo.FetchSurveysScheduler.(sendRequest in _33512DA41A222F7C8E4610617D4948E9)() -> () FetchSurveysScheduler.swift:0

closure #1 (Foundation.Data?, __C.NSURLResponse?, Swift.Error?) -> () in Qualaroo.FetchSurveysOperation.fetchSurveys(with: (Qualaroo.FetchSurveysResult) -> ()) -> () FetchSurveysOperation.swift:39
```

---

**Racing condition**

FetchSurveysScheduler.fetchSurveys calls consecutively setNewTimer and tryToSendRequest. BOTH setNewTimer and tryToSendRequet execute -> tryToSendRequest which upon completion of FetchSurveyOperation call self?.delegate?.fetchedSurveys(surveys). 

**Solution:** The delegate in this case is Qualaroo.fetchedSurveys. It assigns surveys to its local copy of surveys regardless of the calling thread. Assignment in this case requires synchronization otherwise it can lead to unspecified behavior and crash the app as seen above. 

**Improvement:**
After setNewTimer it is unnecessary to invoke tryToSendRequest. 

should be:
`func fetchSurveys() {
    setNewTimer() 
  }`
instead of:
`func fetchSurveys() {
    setNewTimer()
    tryToSendRequest()
  }`

**Dead timer** 

FetchSurveysScheduler.setNewTimer is broken. The timer fires once and never again. The reason is described in the apple documentation: https://developer.apple.com/documentation/foundation/timer @see Scheduling Timers in Run Loops ::  init(timeInterval:invocation:repeats:)

> Use the init(timeInterval:invocation:repeats:) or init(timeInterval:target:selector:userInfo:repeats:) class method to create the timer object without scheduling it on a run loop. (**After creating it, you must add the timer to a run loop manually by calling the add(_:forMode:) method of the corresponding RunLoop object.**)

**Solution:**
Replacing:
`Timer(timeInterval: time, target: self, selector: #selector(tryToSendRequest), userInfo: nil, repeats: true)`
with:
`Timer.scheduledTimer(timeInterval: time, target: self, selector: #selector(tryToSendRequest), userInfo: nil, repeats: true)`

should resolve this issue and the timer will start firing again.

*Note: You could also add manually to the run loop but IMO the solution above is cleaner.*

**Comment by scana** [comment]
Those are fantastic finds and we really appreciate provided solutions. Thank you so much, I will release both of those fixes it in a minute or two.
Thank you @r1c4r60 for pointing and explaining those and also thank you @pyrtsa for fixing those with two small and straightforward PRs :)

I will allow myself to close this issue - hopefully it there won't be any need to reopen :)
