### ISSUE TITLE
NPS Score Slider is Black

### ISSUE THREAD

**Issue by bradley-rover** [qualaroo/QualarooSDKiOS#14]
Qualaroo SDK 1.13.1 installed via cocoapods
Test flight build, on iPhone 10, iOS 13.5.1
--------------------------------------------

See the screenshot below:
<img width="390" alt="Screen Shot 2020-08-10 at 1 18 16 PM" src="https://user-images.githubusercontent.com/44174074/89827806-f8e3f180-db0c-11ea-864c-d63032aba13a.png">

Let me know if you need more info!

**Comment by durgeshqualaroo** [comment]
The problem was resolved.
