### ISSUE TITLE
SurveyButtonsView.xib not found

### ISSUE THREAD

**Issue by lauramejiaarroyave** [qualaroo/QualarooSDKiOS#17]
After install  the library with cocoa pods, I got this error.

Maybe is for another installed library?
Is not possible for me to uninstall them to identify which causes the error.

Thoughts?

./Pods/Qualaroo/Qualaroo/Survey/Footer/**SurveyButtonsView.xib not found**
Command PhaseScriptExecution failed with a nonzero exit code

![Screen Shot 2020-11-09 at 6 51 19 AM](https://user-images.githubusercontent.com/11670941/98537941-0584fc80-2258-11eb-84b4-e06ee8d016c9.png)

**Comment by durgeshqualaroo** [comment]
The exception was handled under latest release. Please connect at support@proprofs.com if you still experiencing this problem.
