### ISSUE TITLE
Support for Swift 4.2

### ISSUE THREAD

**Issue by eneko** [qualaroo/QualarooSDKiOS#2]
Would like support for Swift 4.2, currently cannot use Qualaroo with Xcode 10 GM.

**Comment by scana** [comment]
Hi @eneko!

Could you please try our latest release: https://github.com/qualaroo/QualarooSDKiOS/releases/tag/1.8.2
It's been recompiled in order to work with Xcode 10.
Sorry it took so long.

**Comment by eneko** [comment]
HI @scana,

Testing this now, it seems that 1.8.2 is not yet available via CocoaPods?

Eneko

**Comment by eneko** [comment]
Never mind, I see the update now.
