### ISSUE TITLE
OpeningFilter preventing survey from being displayed to different users on the same device

### ISSUE THREAD

**Issue by Lukaz32** [qualaroo/QualarooSDKiOS#20]
I have this survery that I intend to display only once per user. I'm currently setting the userID like so
```swift
Qualaroo.shared.setUserID(myUser.id)
```

The problem is that after displaying the survey once to **User A** and loging into **User B**, the SDK would throw
```
[Qualaroo]: Not showing survey with id: 010101.
User have already seen this survey, and it should be seen only once.
```

even though `setUserID` and `config` are being called again with the correct `id` from **User B**.

On checking the SDK code I found this specific filter to be preventing the survey to be displayed: `OpeningFilter`
It seems to be persisting info to _UserDefaults_ which isn't overridden when a new UserID is set via 
```swift
Qualaroo.shared.setUserID(myUser.id)
```

Is there any way to disable that filter? or am I missing something else?

Thanks in avance

**Comment by durgeshqualaroo** [comment]
@Lukaz32 Would you be able to connect with us at support@proprofs.com if you still have this issue open? We'll arrange a call to understand this requirement and to suggest an appropriate solution. Thank you.
