### ISSUE TITLE
Progress bar overlapped with buttons

### ISSUE THREAD

**Issue by ponsuyambu** [qualaroo/QualarooSDKiOS#8]
Hi,

Please find the attached screenshot. 

![unnamed (3)](https://user-images.githubusercontent.com/4482905/64426970-49a6cb00-d0b0-11e9-8f65-85cf687f9116.jpg)

The progress bar is overlapped on top of the buttons. Could you fix asap?

Device used: iPhone XS
Qualaroo SDK version: 1.10.0

Thanks,
Pons

**Comment by scana** [comment]
Hi @ponsuyambu!
Sorry for such a delay. This issue should be resolved with version `1.12.1`.

Please reopen this issue if the problem persists.
